### PR TITLE
Adding something

### PR DESCRIPTION
**Pull request by dastangoo**

### CODE REVIEW

**Comment by soshianet-110** [comment]
That's a good idea.

**Comment by dastangoo** [comment]
Hey @soshianet-110 , do you really think it's a good idea for such a project?

**Comment by soshianet-110** [comment]
I don't follow what do you mean by this!?

**Comment by soshianet-110** [comment]
My friend @dastangoo, can  you elaborate more on this?

**Comment by dastangoo** [comment]
@soshianet-110 , Let's merge this and close it.

**Pull request merged**
